s8d.oss:
  local.uploadRootPath: /s8d/oss

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/oss?characterEncoding=UTF-8&useSSL=true
    username: ossuser
    password: ossuser
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://springboot-embedded-server:9000/auth/realms/springseeds/protocol/openid-connect/certs


