server:
  servlet.context-path: /oss-local
  port: 9020

spring:
  application:
    name: oss-local-server
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oss?characterEncoding=UTF-8&useSSL=true
    username: ossuser
    password: ossuser
  security:
    oauth2:
      resourceserver:
        jwt:
          # 需要在host文件中定义auth-server服务地址
          jwk-set-uri: http://auth-server:9000/auth/realms/springseeds/protocol/openid-connect/certs
  servlet:
    # 文件上传
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB

s8d.oss:
  local.uploadRootPath: ${user.home}/.s8d



