s8d.oss:
  local.uploadRootPath: ${user.home}/.s8d/oss

spring:
  # JPA配置
  jpa:
    show-sql: true
    format-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oss?characterEncoding=UTF-8&useSSL=true
    username: ossuser
    password: ossuser
  security:
    oauth2:
      resourceserver:
        jwt:
          # 需要在host文件中定义auth-server服务地址
          jwk-set-uri: http://auth-server:9000/auth/realms/springseeds/protocol/openid-connect/certs

