server:
  servlet.context-path: /oss-local
  port: 9020

spring:
  application:
    name: oss-local-server
  # JPA配置
  jpa:
    open-in-view: false

  servlet:
    # 文件上传
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB

# 日志配置
logging:
  level:
    ROOT: INFO
    "[cn.springseed]": DEBUG    
    "[org.springframework.security]": DEBUG
    "[org.springframework.web]": DEBUG



