server:
  servlet.context-path: /oss-minio
  port: 9020

spring:
  application:
    name: oss-minio-server
  security:
    oauth2:
      resourceserver:
        jwt:
          # 需要在host文件中定义auth-server服务地址
          jwk-set-uri: http://auth-server:9000/auth/realms/springseeds/protocol/openid-connect/certs
  servlet:
    # 文件上传
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB

s8d.oss:
  minio.server:
    endpoint: 127.0.0.1
    port: 8001
    accessKey: admin
    secretKey: 12345678



